#!/usr/bin/python

# Project Euler Problem 2
# -----------------------
# Even Fibonacci Numbers:
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2 , the first 10 terms will be:
#   1,2,3,5,8,13,21,34,55,89,...
# By considering the term in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def even_fibseq(n):
    seq = []
    a,b = 1,1
    while b < n:
        a,b = b, a+b
        seq.append(a)
    return filter(lambda x: x % 2 == 0, seq)

print(sum(even_fibseq(4*10**6)))

